#LSTM
output_dim: 1
bidirectional: True


#Transformer
num_heads: 8
num_layers: 4
learning_rate: 0.001

#Training
hidden_dim: 256
embedding_dim: 128
num_epochs: 20
dropout: 0.1
model: Transformer #LSTM or Transformer

